swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:

# LOGIN

  '/login':
    x-swagger-router-controller: login
    post:
      description: login local user
      operationId: loginLocal
      tags:
        - login
      parameters:
          - name: login
            in: body
            required: true
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  '/login/facebook':
    x-swagger-router-controller: login
    post:
      description: login facebook user
      operationId: loginFacebook
      tags:
        - login
      parameters:
          - name: login
            in: body
            required: true
            schema:
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                facebook_id:
                  type: string
                gender:
                  type: string
                profile_picture:
                  type: string
              required:
                - first_name
                - last_name
                - email
                - facebook_id
                - gender
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  '/login/google':
    x-swagger-router-controller: login
    post:
      description: login google user
      operationId: loginGoogle
      tags:
        - login
      parameters:
          - name: login
            in: body
            required: true
            schema:
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                google_id:
                  type: string
                gender:
                  type: string
                profile_picture:
                  type: string
              required:
                - first_name
                - last_name
                - email
                - google_id
                - gender
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

# SIGNUP

  '/signup':
    x-swagger-router-controller: signup
    post:
      description: signup local user
      operationId: signupLocal
      tags:
        - signup
      parameters:
          - name: signup
            in: body
            required: true
            schema:
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                gender:
                  type: string
                password:
                  type: string
                user_type:
                  type: string
              required:
                - first_name
                - last_name
                - email
                - gender
                - password
                - user_type
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  '/signup/facebook':
    x-swagger-router-controller: signup
    post:
      description: signup facebook user
      operationId: signupFacebook
      tags:
        - signup
      parameters:
          - name: signup
            in: body
            required: true
            schema:
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                facebook_id:
                  type: string
                gender:
                  type: string
                profile_picture:
                  type: string
                user_type:
                  type: string
              required:
                - first_name
                - last_name
                - email
                - facebook_id
                - gender
                - user_type
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  '/signup/google':
    x-swagger-router-controller: signup
    post:
      description: signup google user
      operationId: signupGoogle
      tags:
        - signup
      parameters:
          - name: signup
            in: body
            required: true
            schema:
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                google_id:
                  type: string
                gender:
                  type: string
                profile_picture:
                  type: string
                user_type:
                  type: string
              required:
                - first_name
                - last_name
                - email
                - google_id
                - gender
                - user_type
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

# TUTOR

  '/tutor':
    x-swagger-router-controller: tutor
    get:
      description: Get tutors by parameter
      operationId: getTutorsByParameter
      tags:
        - Tutor
      parameters:
          -
            name: city
            in: query
            description: city of tutors
            required: false
            type: string
          -
            name: email
            in: query
            description: tutor with email
            required: false
            type: string
          -
            name: lat
            in: query
            description: latitude of location (coupled with longitude)
            required: false
            type: number
          -
            name: lng
            in: query
            description: longitude of location (coupled with latitude)
            required: false
            type: number
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
    post:
      description: create new tutor
      operationId: createTutor
      tags:
        - Tutor
      parameters:
          - name: tutor
            in: body
            required: true
            schema:
              properties:
                first_name: 
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                short_description:
                  type: string
                full_description:
                  type: string
                city:
                  type: string
                hourly_rate:
                  type: number
                location_lat:
                  type: number
                location_lng:
                  type: number
                travel_distance:
                  type: number
                hours_worked:
                  type: number
                rating: 
                  type: number
                skills:
                  type: array
                  items:
                    type: string
                profile_picture:
                  type: string
              required:
                - first_name
                - last_name
                - email

      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  '/tutor/{tutorId}':
    x-swagger-router-controller: tutor
    get:
      description: get tutor profile information
      operationId: getTutorById
      tags:
        - Tutor
      parameters:
          -
            name: tutorId
            in: path
            required: true
            type: string
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"

  '/tutor/{tutorId}/reviews':
    x-swagger-router-controller: tutor
    get:
      description: get tutor profile information
      operationId: getTutorReviewsById
      tags:
        - Tutor
      parameters:
          -
            name: tutorId
            in: path
            required: true
            type: string
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"

  '/tutor/{tutorId}/schedule':
    x-swagger-router-controller: tutor
    get:
      description: get tutor profile information
      operationId: getTutorScheduleByTutorId
      tags:
        - Tutor
      parameters:
          -
            name: tutorId
            in: path
            required: true
            type: string
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"

# TUTOR SESSION

  '/session/tutor':
    x-swagger-router-controller: session
    get:
      description: Get sessions belonging to tutor email.
      operationId: getTutorSessionByEmail
      tags:
        - Session
      parameters:
          -
            name: email
            in: query
            description: sessions for tutors
            required: true
            type: string
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"

# TUTEE SESSION

  '/session/tutee':
    x-swagger-router-controller: session
    get:
      description: Get sessions belonging to tutee email.
      operationId: getTuteeSessionByEmail
      tags:
        - Session
      parameters:
          -
            name: email
            in: query
            description: sessions for tutees
            required: true
            type: string
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
    post:
      description: create new session
      operationId: createSession
      tags:
        - Session
      parameters:
          - name: session
            in: body
            required: true
            schema:
              properties:
                tutor_email: 
                  type: string
                tutee_email:
                  type: string
                subject:
                  type: string
                datetime:
                  type: string
                duration:
                  type: number
                hourly_rate:
                  type: number
              required:
                - tutor_email
                - tutee_email
                - subject
                - datetime

      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
